dist: xenial

language: perl
perl:
  - "5.26"

env:
  global:
    - NUODB_HOME=/opt/nuodb
    - TZ=America/New_York
    - NUO_ADD_DOMAIN_PASS=yes
    - NUO_START_AGENT=yes
  matrix:
    - NUO_VERSION=3.2.2.1
    - NUO_VERSION=3.3.0.1

notifications:
  recipients:
    - drivers@nuodb.com

before_install:
  - echo madvise | sudo tee /sys/kernel/mm/transparent_hugepage/enabled >/dev/null
  - echo madvise | sudo tee /sys/kernel/mm/transparent_hugepage/defrag >/dev/null
  - wget -q "http://download.nuohub.org/nuodb-ce_${NUO_VERSION}_amd64.deb" --output-document=/var/tmp/nuodb.deb
  - sudo dpkg -i /var/tmp/nuodb.deb

install:
  - cpanm -v --notest --skip-satisfied DBI
  - perl Makefile.PL --nuodb-includes="$NUODB_HOME/include" --nuodb-libs="$NUODB_HOME/lib64"
  - make

before_script:
  - if [ "$NUO_ADD_DOMAIN_PASS" = yes ]; then printf '\ndomainPassword = bird\n' | sudo tee -a "$NUODB_HOME"/etc/default.properties >/dev/null; fi
  - if [ "$NUO_START_AGENT" = yes ]; then sudo service nuoagent start; fi
  - ${NUODB_HOME}/bin/nuodbmgr --broker localhost --password bird --command "start process sm database test host localhost archive /tmp/nuoarchive initialize true"
  - ${NUODB_HOME}/bin/nuodbmgr --broker localhost --password bird --command "start process te database test host localhost options '--dba-user dba --dba-password goalie'"

script:
  - make test

after_failure:
  - cat "$NUODB_HOME"/etc/default.properties
  - cat /var/log/nuodb/agent.log
