language: java

jdk:
  - openjdk7

env:
  - NUODB_VERSION=2.1.1.10_amd64 NUODB_ROOT=/opt/nuodb NUODB_INCLUDE_DIR=/opt/nuodb/include NUODB_LIB_DIR=/opt/nuodb/lib64
  - NUODB_VERSION=2.0.4.24_amd64 NUODB_ROOT=/opt/nuodb NUODB_INCLUDE_DIR=/opt/nuodb/include NUODB_LIB_DIR=/opt/nuodb/lib64

notifications:
  recipients:
    - buck.robert.j@gmail.com
    - rbuck@nuodb.com

before_install:
  - sudo apt-get install perl
  - wget -q http://download.nuohub.org/nuodb_${NUODB_VERSION}.deb --output-document=/var/tmp/nuodb.deb
  - sudo dpkg -i /var/tmp/nuodb.deb
  - sleep 2
  - ${NUODB_ROOT}/bin/nuodb --chorus test --password bar --dba-user dba --dba-password goalie --verbose debug --archive /var/tmp/nuodb --initialize --force &
  - sleep 2
  - ${NUODB_ROOT}/bin/nuodb --chorus test --password bar --dba-user dba --dba-password goalie &
  - sleep 2

script:
  - perl Makefile.PL --nuodb-includes=${NUODB_INCLUDE_DIR} --nuodb-libs=${NUODB_LIB_DIR}
  - make test

after_script:
  - sudo dpkg -r nuodb
